spring.application.name=resume-app

# Springdoc OpenAPI - Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Local development profile
spring.profiles.active=local
server.port=8080
logging.level.com.mlm=INFO

# DynamoDB local (when running DynamoDB Local on the host)
aws.dynamodb.endpoint=http://localhost:8000
aws.region=us-east-1
aws.accessKeyId=dummy
aws.secretAccessKey=dummy
