# Properties for local development (activate with -Dspring.profiles.active=local or SPRING_PROFILES_ACTIVE=local)
server.port=8080
logging.level.com.mlm=DEBUG
app.cors.allowed-origins=http://localhost:4200

# DynamoDB local endpoint
aws.dynamodb.endpoint=http://localhost:8000
aws.region=eu-central-1
aws.accessKeyId=dummy
aws.secretAccessKey=dummy
