# Properties for local development (activate with -Dspring.profiles.active=local or SPRING_PROFILES_ACTIVE=local)
server.port=8080
logging.level.com.mlm=DEBUG
spring.application.name=resume-app
app.cors.allowed-origins=http://localhost:4200

# Springdoc OpenAPI - Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
