# Properties generali dell'applicazione
server.port=8080
logging.level.com.mlm=INFO
spring.application.name=resume-app
#TODO app.cors.allowed-origins=http://localhost:4200

# Springdoc OpenAPI - Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
